[world]
kind = "WorldContract"
class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
original_class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x8d26f23835b0e48a12d7bbc155662523645bf817700611473a8a729a610b92"
transaction_hash = "0x236798bdf001cb632199c59563b3d4d9cb5f95a0ab3f87976f613293fd1d98b"
block_number = 3
seed = "zkchase"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x27b21e585a6e4c196ddf72725edb02be2f675df44c9283ce27f44d5072e5add"
class_hash = "0x707df706a381cfd5eb569f26e87f873fc254f2364ded621059ed2ee8e2544d0"
original_class_hash = "0x707df706a381cfd5eb569f26e87f873fc254f2364ded621059ed2ee8e2544d0"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/zkchase-actions-4ddc6f44.json"
reads = []
writes = [
    "zkchase-Player",
    "zkchase-Game",
    "zkchase-Chaser",
]
init_calldata = []
tag = "zkchase-actions"
manifest_name = "zkchase-actions-4ddc6f44"

[[models]]
kind = "DojoModel"
class_hash = "0x430849e90f7356c49266e6ade7f462c1feffb9205e2ebd4c8db134dc7b53f42"
original_class_hash = "0x430849e90f7356c49266e6ade7f462c1feffb9205e2ebd4c8db134dc7b53f42"
abi = "manifests/dev/deployment/abis/models/zkchase-Chaser-3505463e.json"
tag = "zkchase-Chaser"
manifest_name = "zkchase-Chaser-3505463e"

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "position"
type = "u8"
key = false

[[models.members]]
name = "alive"
type = "bool"
key = false

[[models.members]]
name = "invincible"
type = "bool"
key = false

[[models.members]]
name = "kill_count"
type = "u32"
key = false

[[models.members]]
name = "treasury_count"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x61b05d69f4433bd974d309fae640323ca047e31710c0b0f0d99f67088060a19"
original_class_hash = "0x61b05d69f4433bd974d309fae640323ca047e31710c0b0f0d99f67088060a19"
abi = "manifests/dev/deployment/abis/models/zkchase-Game-264c1ec0.json"
tag = "zkchase-Game"
manifest_name = "zkchase-Game-264c1ec0"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "map_id"
type = "u8"
key = false

[[models.members]]
name = "treasury"
type = "u8"
key = false

[[models.members]]
name = "chasers"
type = "felt252"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5d2da63fed33e7df27075238f5734a35129978d7f70165214db3a34f39d7948"
original_class_hash = "0x5d2da63fed33e7df27075238f5734a35129978d7f70165214db3a34f39d7948"
abi = "manifests/dev/deployment/abis/models/zkchase-Player-2999ddc5.json"
tag = "zkchase-Player"
manifest_name = "zkchase-Player-2999ddc5"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "game_id"
type = "u32"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false
