[world]
name = "ZK-Chase"
description = "A fully on-chain chase game."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "zkchase-v1"

[namespace]
default = "zkchase"

[env]
rpc_url = "https://api.cartridge.gg/x/zkchase/katana"
account_address = "0x17f4e31323c69c5b74e356f9377453a087299f8919ca408a9b180307bd8fa9e"
private_key = "0x20dbdc5fccdb7be69e497a92ba33ef19d81935b84e13e41ae6472f2b388c1a5"

[socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"
