[world]
name = "ZK-Chase"
description = "A fully on-chain chase game."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "zkchase"

[namespace]
default = "zkchase"

[env]
rpc_url = "https://api.cartridge.gg/x/zkchase/katana"
account_address = ""
private_key = ""

[socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"
