[package]
cairo-version = "=2.7.0-rc.3"
name = "zkchase"
version = "0.0.0"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo clean && sozo build && sozo migrate plan && sozo migrate apply"
slot = "sozo --profile slot clean && sozo --profile slot build && sozo --profile slot migrate plan && sozo --profile slot migrate apply"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.4" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
account_address = "0x6b86e40118f29ebe393a75469b4d926c7a44c2e2681b6d319520b7c1156d114"
private_key = "0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b"

[profile.slot.tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/zkchase/katana"
account_address = ""
private_key = ""

[profile.sepolia.tool.dojo.env]
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
account_address = ""
private_key = ""

[tool.dojo.world]
name = "ZK-Chase"
description = "A fully on-chain chase game."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "zkchase"

[tool.dojo.world.namespace]
default = "zkchase"

[tool.dojo.world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"
